---
title: "DS 6388 Spring 2025"
author: "Rene Gutierrez University of Texas at El Paso"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  #bookdown::pdf_book: default
---

# DS 6388: Multivariate Statistical Methods for High-dimensional Data

This is the website for DS 6388. It contains relevant information for the course
and lecture notes.

## Calendar

### Importatnt Dates

* February 10: Linear Algebra Extra Credit Test
* March 2:     First Project Submission Deadline
* March 25:    Second Project Submission Deadline

### Class Schedule

* Class 1:  Introduction to Multivariate High-Dimensional Methods
* Class 2:  HD Linear Regression: Machine Learning
* Class 3:  HD Linear Regression: Bayesian Methods
* Class 4:  Computational Implementation of HD Linear Regression
* Class 5:  Efficient Computation of HD Linear Regression
* Class 6:  Bonus Linear Algebra Test
* Class 7:  Introduction to PCA
* Class 8:  HD PCA
* Class 9:  Principal Components Regression
* Class 10: Factor Analysis 1
* Class 11: Factor Analysis 2
* Class 12: Canonical Correlation Analysis
* Class 13: HD Canonical Correlation Analysis
* Class 14: Project 2
* Class 15: K-Means Part 1
* Class 16: K-Means Part 2
* Class 17: Expectation Maximization
* Class 18: Gaussian Mixture Models (GMM)
* Class 19: HD GMM
* Class 20: Project 3
* Class 21: Logistic Regression
* Class 22: Support Vector Machines
* Class 23: SVM Part 2
* Class 24: Decision Tree Learning